app_name: scanner_bsc_testnet

chain:
  name: "bsc_testnet"
  chain_id: 97
  genesis_block_hash: "0x6d3c66c5357ec91d5c43af47e234a939b22557cbb552dc45bebbceeed90fbe34"
  reversible_blocks: 5

fetch:
  rpc_nodes:
    - "http://127.0.0.1:8545"

  timeout: 5s
  start_height: -1 #if db has blocks, this config would be ignored
  end_height:  -1
  #With internal txs, all account balance changed action and all contract created action could be captured.
  #But this api need archive node, and always it is not free.
  #If set false, balanceChanged and contractCreated is incomplete.
  #For test, set false is ok.
  enable_internal_tx: true

store:
  host: "root:123456@tcp(127.0.0.1:3306)/scanner_bsc_testnet?charset=utf8mb4"
  channel_size: 100
  batch_size: 100
  worker_count: 8
  auto_create_tables: true # prd environment set false

publish:
  kafka_servers:
    - "127.0.0.1:9092"
  topic: "scanner_bsc_testnet"
  channel_size: 100

#panic=0, fatal=1, error=2, warn=3, info=4, debug=5, trace=6, 
log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "./log/app.log"
    level: 5
  kafka:
    enable: false
    topic: "applog"
    kafka_servers:
      - "127.0.0.1:9092"
    level: 5

